### PR TITLE
Codegen Async compatible library

### PR DESCRIPTION
**Pull request by rdavison**
Ref: https://github.com/andrenth/ocaml-swagger/issues/2

- Adds the ability to code-generate an async-compatible library

One thing I was confused about was the need for the `?ctx` param on the http backed functions.  I couldn't tell if there was a parallel feature in cohttp-async, so I removed the optional argument when code-generating the async library.

### CODE REVIEW

**Comment by andrenth** [comment]
I believe `?ctx` is needed to create a cohttp HTTPS client.

**Comment by andrenth** [comment]
Do you think the async version should have the `?ssl_options` parameter, or is it possible to make HTTPS requests without it in cohttp-async?

**Comment by andrenth** [comment]
Some awesome work here, lots of stuff! Are you still working on it? Would you like me to merge it now or wait a bit more?

**Comment by rdavison** [comment]
Hey!  Actually didn't mean to trigger any alerts or anything yet.  The code quality and commit messages are a bit.... dubious... since I wasn't really preparing to get it merged any time soon :sweat_smile: .

In any case, it would be nice to eventually get these changes merged, but I'm not in a rush.

A high level overview:

- [x] Code generates an Async compatible library. (not satisfied with the directory structure yet...)
- [x] Include vendor extensions in the AST. (most of them, anyways, I think there are a few that I deliberately skipped because it would require changing some ATD types).
- [x] Expose some data types (maybe not necessary?) to make it easier for other libraries to manipulate the AST.
- [x] Allow code generation of streaming HTTP requests.  AFAIK it's only Async compatible.  I think a Lwt version should be included before we merge?

**Pull request closed without merging**
